name: 'scooters_dbt'
version: '1.0.0'
profile: 'scooters_dbt'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:        
  - "target"
  - "dbt_packages"
models:
  scooters_dbt:
    +materialized: "table"
    +on_schema_change: "append_new_columns"
    +persist_docs:
      relation: true
      columns: true
seeds:
  scooters_dbt:
    +persist_docs:
      relation: true
      columns: true