scooters_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: dev
      database: dev
      host:  
      port: 8123  # If not set, defaults to 8123, 8443, 9000, 9440 depending on the secure and driver settings 
      user: default # User for all database operations
      password:  # Password for the user
      secure: False
      threads: 2